#!/bin/zsh


export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.poetry/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

export EDITOR="nvim"
export ZSH="$HOME/.oh-my-zsh"

export FZF_TMUX_OPTS="-p"
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --color=bg+:#363646,gutter:-1'


# Macos specific
if [[ "$OSTYPE" == darwin* ]]; then
	export PATH=/opt/homebrew/bin:$PATH
	export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"
	export CPATH=`xcrun --show-sdk-path`/usr/include:/usr/local/include
	export LIBRARY_PATH=/usr/local/opt/openssl/lib/:/usr/local/lib
	export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
	export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
fi
