#!/bin/zsh

setopt nullglob

# Source any files that match the pattern .zprofile.*
for file in $HOME/.zprofile.*; do
    source $file
done

export ZSH="$HOME/.oh-my-zsh"

plugins=(
    zsh-vi-mode
    zsh-autosuggestions
    zsh-syntax-highlighting
    git
    asdf
)
source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# ZVM Configuration -------------------------------------------------------------------------------
# Always starting with insert mode for each command line
ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLOCK
export ZVM_VI_EDITOR=$EDITOR
export ZVM_CURSOR_STYLE_ENABLED=true

function zvm_after_init() {
	source ~/.zprofile
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
  source $ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
}
# ------------------------------------------------------------------------------------------------

# ================================================ Evals =========================================================================
alias ls="exa --icons --group-directories-first"

eval "$(direnv hook zsh)"
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"


# ================================================ Aliases =======================================================================
# General
alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias c="clear"
alias e="exit"

alias cd="z"
alias cat="bat"
alias ls="exa --icons --group-directories-first"

# Python
alias po="poetry"
alias pip="pip3"

# Others
alias fzf="fzf-tmux -p"
alias vv="fzf --reverse --print0 | xargs -0 -o nvim"

alias we="watchexec"
