#!/bin/zsh

setopt nullglob

plugins=(
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source "$HOME/.zsh/aliases.zsh"
source "$HOME/.zsh/functions.zsh"

eval "$(starship init zsh)"

if [[ "$OSTYPE" == darwin* ]]; then
	eval "$(/opt/homebrew/bin/brew shellenv)"
	source ~/.orbstack/shell/init.zsh 2>/dev/null || :
fi

