#!/usr/bin/env bash
set -eu

items="dotfiles
nix
git
diff
docker
kuberentes
monitor
"

chosen=$(printf "$items" | fzf --prompt="  Launch: " --height=100% --border=none)

[ -z "$chosen" ] && exit 0

case "$chosen" in
  dotfiles)   tmux new-window -n dotfiles   -c "$HOME/.local/share/chezmoi" chezmoi edit ;;
  nix) tmux new-window -n nix   -c "$HOME/.local/share/nix-config" nvim ;;
  infra) tmux new-window -n nix   -c "$HOME/.local/share/infra" nvim ;;
  git)    tmux new-window -n lazygit    -c "#{pane_current_path}" lazygit ;;
  diff)    tmux new-window -n tuicr    -c "#{pane_current_path}" tuicr ;;
	docker) tmux new-window -n lazydocker lazydocker ;;
  kuberentes)        tmux new-window -n k9s k9s ;;
  monitor)       tmux new-window -n btop btop ;;
esac
