format = """
$character\
$line_break\
 """

right_format = '$status'

[character]
format = '[ \$ ](fg:#54546d)'

[status]
style = "fg:#E82424"
format = '[$status]($style)'
disabled = false


# The following modules are customized for tmux status line
[directory]
style = "fg:#54546d"
format = "$read_only $path "
read_only = "[-]"

[git_branch]
symbol = ''
format = '| $symbol $branch(:$remote_branch) '

[kubernetes]
symbol = "󱃾 "
format = '| $symbol $context \($namespace\) '
disabled = false

[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:(?P<region>[^:]+):[^:]+:cluster/(?P<cluster>.*)"
context_alias = "eks-$cluster[$region]"

[docker_context]
symbol = '󰡨 '
format = '| $symbol $context '
disabled = false
only_with_files = false

[username]
format = '| $user'
disabled = false
show_always = false

[hostname]
ssh_only = true
format = '@$hostname'
disabled = false
